from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(292, 310)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 200, 271, 51))
        self.groupBox.setObjectName("groupBox")
        self.generateSpreadChk = QtWidgets.QCheckBox(self.groupBox)
        self.generateSpreadChk.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.generateSpreadChk.setObjectName("generateSpreadChk")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 271, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(151, 21, 111, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.zipCodeInput = QtWidgets.QLineEdit(self.widget)
        self.zipCodeInput.setMaximumSize(QtCore.QSize(113, 20))
        self.zipCodeInput.setObjectName("zipCodeInput")
        self.verticalLayout_2.addWidget(self.zipCodeInput)
        self.cityInput = QtWidgets.QLineEdit(self.widget)
        self.cityInput.setMaximumSize(QtCore.QSize(113, 20))
        self.cityInput.setObjectName("cityInput")
        self.verticalLayout_2.addWidget(self.cityInput)
        self.radiusInput = QtWidgets.QLineEdit(self.widget)
        self.radiusInput.setMaximumSize(QtCore.QSize(113, 20))
        self.radiusInput.setObjectName("radiusInput")
        self.verticalLayout_2.addWidget(self.radiusInput)
        self.limitInput = QtWidgets.QLineEdit(self.widget)
        self.limitInput.setObjectName("limitInput")
        self.verticalLayout_2.addWidget(self.limitInput)
        self.keywordsInput = QtWidgets.QLineEdit(self.widget)
        self.keywordsInput.setObjectName("keywordsInput")
        self.verticalLayout_2.addWidget(self.keywordsInput)
        self.widget1 = QtWidgets.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(11, 21, 140, 161))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 290, 41, 16))
        self.label_6.setObjectName("label_6")
        self.statusOutput = QtWidgets.QLabel(Dialog)
        self.statusOutput.setGeometry(QtCore.QRect(50, 290, 231, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusOutput.setFont(font)
        self.statusOutput.setTextFormat(QtCore.Qt.AutoText)
        self.statusOutput.setObjectName("statusOutput")
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(30, 250, 231, 41))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.widget2)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.clearButton = QtWidgets.QPushButton(self.widget2)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Spreadsheet Options"))
        self.generateSpreadChk.setText(_translate("Dialog", "Generate Spreadsheet"))
        self.groupBox_2.setTitle(_translate("Dialog", "Search Options"))
        self.keywordsInput.setText(_translate("Dialog", "pain,ortho,spine"))
        self.label_2.setText(_translate("Dialog", "Search from Zipcode"))
        self.label_3.setText(_translate("Dialog", "Search from City"))
        self.label_4.setText(_translate("Dialog", "Search Radius (Miles)"))
        self.label_5.setText(_translate("Dialog", "Result Limit"))
        self.label.setText(_translate("Dialog", "Keywords"))
        self.label_6.setText(_translate("Dialog", "Status:"))
        self.statusOutput.setText(_translate("Dialog", "Await input from user"))
        self.startButton.setText(_translate("Dialog", "Generate"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
