# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaxonomyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(514, 330)
        self.add_button = QtWidgets.QPushButton(Form)
        self.add_button.setGeometry(QtCore.QRect(30, 252, 111, 61))
        self.add_button.setObjectName("add_button")
        self.search_box = QtWidgets.QLineEdit(Form)
        self.search_box.setGeometry(QtCore.QRect(10, 10, 501, 20))
        self.search_box.setObjectName("search_box")
        self.taxonomy_list_widget = QtWidgets.QListWidget(Form)
        self.taxonomy_list_widget.setGeometry(QtCore.QRect(10, 40, 501, 192))
        self.taxonomy_list_widget.setObjectName("taxonomy_list_widget")
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setGeometry(QtCore.QRect(360, 252, 91, 61))
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_button.setText(_translate("Form", "Add To Saved"))
        self.exit_button.setText(_translate("Form", "Exit"))
